sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in cloud-user.json.enc -out cloud-user.json -d
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
  - curl https://sdk.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file cloud-user.json
  - gcloud config set project multi-k8s-a
  - gcloud config set compute/zone europe-west6-a
  - gcloud container clusters get-credentials multi-cluster-k8s
  - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_USERNAME" --password-stdin
  - decker build -t kareemelkasaby/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run kareemelkasaby/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master